### ISSUE TITLE
cp: cannot stat '/aws2luks/.profile': No such file or directory

### ISSUE THREAD

**Issue by ghost** [dzaninov/aws2luks#12]
Setting up initramfs-tools (0.122ubuntu8.8) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.122ubuntu8.8) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-71-generic
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
cp: cannot stat '/aws2luks/.profile': No such file or directory
E: /etc/initramfs-tools/hooks/aws2luks failed with return 1.
update-initramfs: failed for /boot/initrd.img-4.4.0-71-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ghost** [comment]
after upgrade.

**Comment by dzaninov** [comment]
Thank you for testing !
I fixed the issue.
https://github.com/dzaninov/aws2luks/commit/7bf789fcbdeea1334f5c52a9f59fbeb63a2d189f#diff-9a07953c97eb6aa2afc2a0137dca4af8
