### ISSUE TITLE
AWS_URL IP Address Invalid

### ISSUE THREAD

**Issue by jordanwilson230** [dzaninov/aws2luks#14]
There are a few places that refer to the AWS_URL env variable which is hard-coded as 169.254.169.254.  This IP is unresponsive and does not appear to be valid.  Could you please explain what the IP was there for so I can replace it?

**Comment by dzaninov** [comment]
That IP is used on AWS to retrieve instance metadata, see:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
